# https://en.wikipedia.org/wiki/Sampling_(signal_processing)#Sampling_rate
SAMPLES_PER_SECOND_OPTIONS = {
    'DEBUG': 8000,
    'TELEPHONE_QUALITY': 16000,
    'RADIO_QUALITY': 32000,
    'DIGITAL_STANDARD': 48000,
    'DIGITAL_RECORDING_STANDARD': 96000,
    'HIGH_DEFINITION': 192000,
}

SAMPLE_BIT_DEPTH_OPTIONS = {
    '8_BIT': 8,
    '16_BIT': 16,
    '32_BIT': 32,
}

BUFFER_MS = 100
AUDIO_STREAM_CHUNK_SIZE = 1024  # AKA "frames per buffer"
SAMPLES_PER_SECOND = SAMPLES_PER_SECOND_OPTIONS['DIGITAL_STANDARD']
SAMPLE_BIT_DEPTH = SAMPLE_BIT_DEPTH_OPTIONS['8_BIT']
NUM_AUDIO_CHANNELS = 1  # e.g. 1=mono; 2=stereo
EVENT_QUEUE_MAX_SIZE = 127
MAX_POLYPHONY = 8  # num notes that can be played simultaneously
